"""add github fetch attempts table

Revision ID: 9cced86d8777
Revises: dbe3b8cfcac5
Create Date: 2026-09-14 13:39:48.446556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cced86d8777'
down_revision: Union[str, Sequence[str], None] = 'dbe3b8cfcac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_fetch_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_fetch_attempts_user_id'), 'github_fetch_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_fetch_attempts_user_id'), table_name='github_fetch_attempts')
    op.drop_table('github_fetch_attempts')
    # ### end Alembic commands ###
