"""initial schema

Revision ID: dbe3b8cfcac5
Revises: 
Create Date: 2026-09-13 23:17:26.322287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbe3b8cfcac5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('charges_truncated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED_PROSECUTION', 'PROSECUTING', 'QUEUED_DEFENSE', 'DEFENDING', 'QUEUED_JUDGMENT', 'JUDGING', 'SENTENCED', 'DISMISSED', 'QUEUED_REJUDGMENT', 'REJUDGING', 'FAILED', name='case_status'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('appeal_used', sa.Boolean(), nullable=False),
    sa.Column('prosecution_attempts', sa.Integer(), nullable=False),
    sa.Column('defense_attempts', sa.Integer(), nullable=False),
    sa.Column('judgment_attempts', sa.Integer(), nullable=False),
    sa.Column('rejudgment_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('failed_stage', sa.Enum('PROSECUTION', 'DEFENSE', 'JUDGMENT', name='failed_stage'), nullable=True),
    sa.Column('failure_reason', sa.Enum('SCHEMA_INVALID', 'TIMEOUT', 'API_ERROR', name='failure_reason'), nullable=True),
    sa.Column('rejudgment_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejudgment_failed_reason', sa.Text(), nullable=True),
    sa.Column('previous_case_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['previous_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_code_hash'), 'cases', ['code_hash'], unique=False)
    op.create_index('ix_cases_status_locked_at', 'cases', ['status', 'locked_at'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_index('uq_cases_active_code', 'cases', ['user_id', 'code_hash', 'language'], unique=True, postgresql_where=sa.text("status NOT IN ('SENTENCED', 'DISMISSED', 'FAILED')"), sqlite_where=sa.text("status NOT IN ('SENTENCED', 'DISMISSED', 'FAILED')"))
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('rebuttal', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('charge_index', sa.Integer(), nullable=False),
    sa.Column('raw_index', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('evidence_start', sa.Integer(), nullable=False),
    sa.Column('evidence_end', sa.Integer(), nullable=False),
    sa.Column('charged_severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severity'), nullable=False),
    sa.Column('severity_adjusted', sa.Boolean(), nullable=False),
    sa.Column('severity_reason', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'charge_index', name='uq_charges_case_index')
    )
    op.create_index(op.f('ix_charges_case_id'), 'charges', ['case_id'], unique=False)
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('opinion', sa.Text(), nullable=False),
    sa.Column('rebuttal_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_overturned', sa.Boolean(), nullable=False),
    sa.Column('precedent_verdict_ids', postgresql.ARRAY(sa.Integer()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_judgments_case_revision')
    )
    op.create_index(op.f('ix_judgments_case_id'), 'judgments', ['case_id'], unique=False)
    op.create_table('pleas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('plea', sa.Enum('ADMIT', 'DENY', 'NO_RESPONSE', name='plea_value'), nullable=False),
    sa.Column('argument', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge_id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('target_start', sa.Integer(), nullable=False),
    sa.Column('target_end', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='effort'), nullable=False),
    sa.Column('effort_adjusted', sa.Boolean(), nullable=False),
    sa.Column('effort_reason', sa.Text(), nullable=True),
    sa.Column('effort_clamped', sa.Boolean(), nullable=False),
    sa.Column('advisory', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_charge_id'), 'sentences', ['charge_id'], unique=False)
    op.create_index(op.f('ix_sentences_judgment_id'), 'sentences', ['judgment_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('SUSTAINED', 'REDUCED', 'DISMISSED', name='verdict_value'), nullable=False),
    sa.Column('final_severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severity'), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_charge_id'), 'verdicts', ['charge_id'], unique=False)
    op.create_index(op.f('ix_verdicts_judgment_id'), 'verdicts', ['judgment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_judgment_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_charge_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_sentences_judgment_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_charge_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_table('pleas')
    op.drop_index(op.f('ix_judgments_case_id'), table_name='judgments')
    op.drop_table('judgments')
    op.drop_index(op.f('ix_charges_case_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_table('appeals')
    op.drop_index('uq_cases_active_code', table_name='cases', postgresql_where=sa.text("status NOT IN ('SENTENCED', 'DISMISSED', 'FAILED')"), sqlite_where=sa.text("status NOT IN ('SENTENCED', 'DISMISSED', 'FAILED')"))
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index('ix_cases_status_locked_at', table_name='cases')
    op.drop_index(op.f('ix_cases_code_hash'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres ENUM types backing these columns
    # (no-op on dialects without native enum support, e.g. SQLite).
    bind = op.get_bind()
    sa.Enum(name='effort').drop(bind, checkfirst=True)
    sa.Enum(name='verdict_value').drop(bind, checkfirst=True)
    sa.Enum(name='plea_value').drop(bind, checkfirst=True)
    sa.Enum(name='severity').drop(bind, checkfirst=True)
    sa.Enum(name='failure_reason').drop(bind, checkfirst=True)
    sa.Enum(name='failed_stage').drop(bind, checkfirst=True)
    sa.Enum(name='case_status').drop(bind, checkfirst=True)
